[package]
name = "banco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-appender = "0.1"

[[bin]]
name = "banco"
path = "src/main.rs"