[package]
name = "banco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comunicacion = { path = "../comunicacion" }
rand = "0.7"


[[bin]]
name = "banco"
path = "src/main.rs"