[package]
name = "alglobo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
actix = "0.11.0"
actix-rt = "2.2"

[[bin]]
name = "procesador_pagos"
path = "src/procesador_pagos.rs"
